### ISSUE TITLE
Send message doesn't work with fresh installed  Version 1.3.2

### ISSUE THREAD

**Issue by fotokloto** [giuseppecastaldo/ha-addons#38]
Error message:
[2023-07-11T14:31:48.975] [ERROR] default - Send message failed. Number 49xxxxxxxxxx@s.whatsapp.net is not on Whatsapp.

Remark:
The given number is a existing Whatsapp account

**Comment by gekberlin** [comment]
Same problem on my site. I have also double checked that the number is correct. 
The strange thing is that with : 49xxxxxxxxxx@s.whatsapp.net](mailto:49xxxxxxxxxx@s.whatsapp.net I get the error message and with 49 **0** xxxxxxxxxx@s.whatsapp.net](mailto:49xxxxxxxxxx@s.whatsapp.net (which is an invalid number because of the leading 0 after the country code) I don't get an error and the message is also visible in my whatsapp app. Of course, the message still can't be delivered because the number is not available. 
Any suggestions @giuseppecastaldo ?

**Comment by C-o-l-u-m-b-o** [comment]
Exact same issue here... 49 correct number => "Number is not on whatsapp"
49 **0**+correct number - I see as outgoing message in my real whatsapp

**Comment by PiperNigrum** [comment]
Any updates for this issue?
Installed the addon an facing this issue...
Tried to send a Message with both account types (WA and WA Business)

**Comment by XtraLarge** [comment]
same problem here

**Comment by PiperNigrum** [comment]
Does anybody of my german colleague solved this Problem?
Maybe I'm wrong but I think this repo is not up to date and also  won't be in future...

**Comment by cosote** [comment]
Hi guys,
I just created a PR that fixes sending messages to users.
Cheers - cosote.

**Comment by fotokloto** [comment]
Good job done, it's now working.

**Comment by cosote** [comment]
> PS: if you need my number for testing/debugging pls send me an pn. PPS: my workaround is actually to create a group with the person and send the message to the group. This works! PPPS: the easiest way to get the group id is:
> 
> 1. Create a group
> 2. add source and destination person to group
> 3. under HA development --> listen to event "new_whatsapp_message"
> 4. send a message to the group
> 5. so you can see the message ..... and the group id :)

Yes - that needs a nice section in docs for time being. I do remember in forced repos I saw some group metadata code... would be nice if the addon could resolve the group (name or invite key) to group-id... it took me some time to read in multiple places to get that sorted out. Anyway, I think this issue can be closed @giuseppecastaldo?
